name: 'action-upload-to-s3'
description: 'Recursively upload folder to S3 bucket'
author: 'core3'
branding:
  icon: 'crosshair'  
  color: 'blue'
inputs:
  aws_secret_id: # change this
    required: true
    description: 'input description here'
  aws_secret_key: # change this
    required: true
    description: 'input description here'
  aws_bucket:
    required: true
    description: 'input description here'
  aws_subfolder:
    required: true
    description: 'input description here'
  folder_to_upload:
    required: true
    description: 'input description here'
runs:
  using: 'node12'
  main: 'dist/index.js'
